spring:
  application:
    name: artist-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 
    url: 
    username: 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 9191
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/